### ISSUE TITLE
Quartz.JobPersistenceException add lock instance error

### ISSUE THREAD

**Issue by CMeyer19** [glucaci/mongodb-quartz-net#13]
Hi i have a question on the following exception.

I am running a dockerised .net core API service that schedules different types of jobs. 

I keep running into this error: Quartz.JobPersistenceException: Unable to add lock instance for lock TriggerAccess on {MachineName}-{Guid}

Is this a fatal error or something i don't need to be concerned about, i only have a singleton scheduler service that is responsible for adding, removing and executing jobs.

I am using a single database with a single container.

The full exception:
`Quartz.JobPersistenceException: Unable to add lock instance for lock TriggerAccess on LAPTOP-CMEYER-fef7cff8-e654-40b8-8dfd-044e3799c6ab ---> System.Exception: Unable to add lock instance for lock TriggerAccess on LAPTOP-CMEYER-fef7cff8-e654-40b8-8dfd-044e3799c6ab
   at Quartz.Spi.MongoDbJobStore.LockManager.AddLock(LockInstance lockInstance) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\LockManager.cs:line 75
   at Quartz.Spi.MongoDbJobStore.LockManager.AcquireLock(LockType lockType, String instanceId) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\LockManager.cs:line 54
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger, CancellationToken cancellationToken) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\MongoDbJobStore.cs:line 201
   --- End of inner exception stack trace ---
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger, CancellationToken cancellationToken) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\MongoDbJobStore.cs:line 214
   at Quartz.Core.QuartzScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Core\QuartzScheduler.cs:line 617
   at Scheduler.SchedulerService.ScheduleTriggerEvaluationAsync(String groudId, String triggerId, Boolean isActivate, DateTimeOffset date) in C:\Sandbox\Server\Server\src\Scheduler.API\Scheduler\SchedulerService.cs:line 58
   at Scheduler.API.Service.SchedulerApi.ScheduleEventAsync(CalendarEventEntity calendarEventEntity) in C:\Sandbox\Server\Server\src\Scheduler.API\Scheduler.API.Service\SchedulerAPI.cs:line 270
   at Scheduler.API.Service.SchedulerApi.EventEntityChangeEventAsync(IRedGreenQueueAdapter redq, JObject jo, String publishKey, String subscribeKey, String replyKey, Hashtable headers) in C:\Sandbox\Server\Server\src\Scheduler.API\Scheduler.API.Service\SchedulerAPI.cs:line 89
   at DAPI.RedGreenQueue.Adapter.RedGreenQueueAdapter.ProcessSubscriptionMessageAsync(String publishKey, String subscribeKey, String replyKey, String message, Func`1 effectiveMessage, Boolean logNoSubscribes, Hashtable headers) [See nested exception: System.Exception: Unable to add lock instance for lock TriggerAccess on LAPTOP-CMEYER-fef7cff8-e654-40b8-8dfd-044e3799c6ab
   at Quartz.Spi.MongoDbJobStore.LockManager.AddLock(LockInstance lockInstance) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\LockManager.cs:line 75
   at Quartz.Spi.MongoDbJobStore.LockManager.AcquireLock(LockType lockType, String instanceId) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\LockManager.cs:line 54
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger, CancellationToken cancellationToken) in C:\Sandbox\Server\Server\src\Scheduler.API\Quartz.Spi.MongoDbJobStore\MongoDbJobStore.cs:line 201]`

![image](https://user-images.githubusercontent.com/29221707/48251517-9840f580-e40a-11e8-9cc2-82fade760295.png)

**Comment by chrisdrobison** [comment]
Did you figure this out?

**Comment by smedet** [comment]
Hello  Chris
I am getting the same exception. Please advise.  

Quartz.JobPersistenceException: Unable to add lock instance for lock TriggerAccess on NON_CLUSTERED ---> System.Exception: Unable to add lock instance for lock TriggerAccess on NON_CLUSTERED
   at Quartz.Spi.MongoDbJobStore.LockManager.AddLock(LockInstance lockInstance)
   at Quartz.Spi.MongoDbJobStore.LockManager.<AcquireLock>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore.<AcquireNextTriggers>d__110.MoveNext()
   --- End of inner exception stack trace ---
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore.<AcquireNextTriggers>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.QuartzSchedulerThread.<Run>d__28.MoveNext() [See nested exception: System.Exception: Unable to add lock instance for lock TriggerAccess on NON_CLUSTERED
   at Quartz.Spi.MongoDbJobStore.LockManager.AddLock(LockInstance lockInstance)
   at Quartz.Spi.MongoDbJobStore.LockManager.<AcquireLock>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore.<AcquireNextTriggers>d__110.MoveNext()]

**Comment by kcragin** [comment]
Anyone have any more thoughts on this or resolution? I'm getting this exception as well.

**Comment by chrisdrobison** [comment]
Now that the new Mongo supports transactions, we could probably replace the lock with a transaction call.


________________________________

**Comment by gabrieligbastos** [comment]
+1, same here =(

**Comment by vnovakovits** [comment]
+1

**Comment by apakbaz** [comment]
Could anyone please elaborate on how to enable clustering to begin with? 
I can't seem to figure that out  :(

**Comment by xico002** [comment]
+1

**Comment by xico002** [comment]
> Did you figure this out?

Do you know why this happens? @chrisdrobison

**Comment by chrisdrobison** [comment]
I don’t. I don’t really maintain the library any more as I’ve moved away from using Quartz for scheduling tasks. I’m open to someone opening a PR.

**Comment by NorekZ** [comment]
@CMeyer19  try v3.0.5, hopefully it was just fixed...

**Comment by glucaci** [comment]
I will close this if was already fixed
