### ISSUE TITLE
MongoDbJobStore fails to initialize when running with MongoDB.Bson 2.4.1

### ISSUE THREAD

**Issue by jpasichnyk** [glucaci/mongodb-quartz-net#4]
I'm migrating to MT3 along with newest MongoDB/Quartz/etc., and am having issues getting your mongodb connector working.  I was using https://github.com/Nanoko/quartznet-mongodb previously, but want Mongodb 2.x driver support. 

When it tries to resolve the scheduler from the factor I get:  
```
The memberInfo argument must be for class JobKey, but was for class Key`1.\r\nParameter name: 
memberInfo
```

It seems to be an issue coming from the BsonSerializer, which doesn't make a ton of sense to me as I'm pointing this thing at a fresh DB (was thinking it might be from existing records in the old db at first).

Thoughts?

I'm using the following setup:

```
var properties = new NameValueCollection
            {
                [StdSchedulerFactory.PropertySchedulerInstanceName] = "MassTransit_QuartzNet",
                [StdSchedulerFactory.PropertySchedulerInstanceId] = $"{Environment.MachineName}-{Guid.NewGuid()}",
                [StdSchedulerFactory.PropertyJobStoreType] = typeof(MongoDbJobStore).AssemblyQualifiedName,
                [
                    $"{StdSchedulerFactory.PropertyJobStorePrefix}.{StdSchedulerFactory.PropertyDataSourceConnectionString}"
                    ] = ConfigurationManager.ConnectionStrings["quartznet-mongodb"].ConnectionString,
                [$"{StdSchedulerFactory.PropertyJobStorePrefix}.collectionPrefix"] = "prefix"
            };
            // I treat the database in the connection string as the one you want to connect to
            // The prefix is optional

            var factory = new StdSchedulerFactory(properties);
```

with app.config records as follows:

```
 <connectionStrings>
    <add name="quartznet-mongodb" connectionString="mongodb://quartznet:passwordhere@mongo1/quartznet" />
  </connectionStrings>
  <quartz>
    <add key="quartz.scheduler.instanceName" value="MassTransit_QuartzNet" />
    <add key="quartz.threadPool.type" value="Quartz.Simpl.SimpleThreadPool, Quartz" />
    <add key="quartz.threadPool.threadCount" value="4" />
    <add key="quartz.threadPool.threadPriority" value="2" />
    <add key="quartz.jobStore.misfireThreshold" value="60000" />
    <add key="quartz.jobStore.type" value="Quartz.Spi.MongoDbJobStore.MongoDbJobStore, Quartz.Spi.MongoDbJobStore" />
  </quartz>
```

**Comment by chrisdrobison** [comment]
Do you have a stack trace at all? Are you sure there is no existing data in the database? I use this library with MT3 and I've never encountered this error, which is why I'm curious.

**Comment by jpasichnyk** [comment]
There is an existing database called "quartz" which does have old data (with "MassTransit" prefix, which is why i updated this to be "MassTransit_QuartzNet"), and that was my original thought, however I updated the connection string to point to "quartznet" instead.  Is there maybe something hardcoded to "quartz" database name?  Let me dig up a stacktrack for you, and thanks so much for the quick response.

**Comment by jpasichnyk** [comment]
Here is the inner exception stacktrace

```
   at MongoDB.Bson.Serialization.BsonClassMap.EnsureMemberInfoIsForThisClass(MemberInfo memberInfo)
   at MongoDB.Bson.Serialization.BsonClassMap.MapMember(MemberInfo memberInfo)
   at MongoDB.Bson.Serialization.Conventions.ImmutableTypeClassMapConvention.Apply(BsonClassMap classMap)
   at MongoDB.Bson.Serialization.Conventions.ConventionRunner.Apply(BsonClassMap classMap)
   at MongoDB.Bson.Serialization.BsonClassMap.AutoMapClass()
   at MongoDB.Bson.Serialization.BsonClassMap.AutoMap()
   at Quartz.Spi.MongoDbJobStore.Repositories.JobStoreClassMap.<>c.<RegisterClassMaps>b__0_2(BsonClassMap`1 map) in D:\github\georiot\core\sln\backend\mongodb-quartz-net\Quartz.Spi.MongoDbJobStore\Repositories\JobStoreClassMap.cs:line 35
   at MongoDB.Bson.Serialization.BsonClassMap`1..ctor(Action`1 classMapInitializer)
   at MongoDB.Bson.Serialization.BsonClassMap.RegisterClassMap[TClass](Action`1 classMapInitializer)
   at Quartz.Spi.MongoDbJobStore.Repositories.JobStoreClassMap.RegisterClassMaps() in D:\github\georiot\core\sln\backend\mongodb-quartz-net\Quartz.Spi.MongoDbJobStore\Repositories\JobStoreClassMap.cs:line 33
   at Quartz.Spi.MongoDbJobStore.MongoDbJobStore..cctor() in D:\github\georiot\core\sln\backend\mongodb-quartz-net\Quartz.Spi.MongoDbJobStore\MongoDbJobStore.cs:line 45
```

and up a level:
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Util\ObjectUtils.cs:line 109
   at Quartz.Impl.StdSchedulerFactory.Instantiate() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\StdSchedulerFactory.cs:line 652
```

**Comment by jpasichnyk** [comment]
@chrisdrobison it must be breaking before even getting to mongo, as if i kill my mongo connection string (replaced it with bad hostname) I get the same error.  Could it have something to do with the actual message its trying to process?

here is a sample message payload (queued through MT3 SchedulePublish method:
```
{

  "messageId": "4be20000-5db3-0015-77d1-08d435b8f840",

  "conversationId": "4be20000-5db3-0015-fd7b-08d435b8f841",

  "sourceAddress": "rabbitmq://mq1-production/bus-PDESK-Test.QueueDelayedMessage.vshost-jxtyyyn7scybko8wbdkdmq8z84?durable=false&autodelete=true",

  "destinationAddress": "rabbitmq://mq1-production/ha.masstransit_quartz",

  "messageType": [

    "urn:message:MassTransit.Scheduling:ScheduleMessage[[Test.QueueDelayedMessage:TestMessage]]",

    "urn:message:MassTransit.Scheduling:ScheduleMessage"

  ],

  "message": {

    "correlationId": "4be20000-5db3-0015-1a35-08d435b8f81f",

    "scheduledTime": "2017-01-05T22:19:56.9030225Z",

    "payloadType": [

      "urn:message:Test.QueueDelayedMessage:TestMessage"

    ],

    "destination": "rabbitmq://mq1-production/Test.QueueDelayedMessage:TestMessage",

    "payload": {

      "correlationGuid": "b3dbd2d4-4a4a-4cba-a145-a1b63deaa2a5",

      "createdAt": "2017-01-05T22:19:51.9025213Z",

      "text": "testing delayed message publishing!"

    }

  },

  "headers": {},

  "host": {

    "machineName": "PDESK",

    "processName": "Test.QueueDelayedMessage.vshost",

    "processId": 17580,

    "assembly": "Test.QueueDelayedMessage",

    "assemblyVersion": "1.0.0.0",

    "frameworkVersion": "4.0.30319.42000",

    "massTransitVersion": "3.5.0.899",

    "operatingSystemVersion": "Microsoft Windows NT 6.2.9200.0"

  }

}
```

**Comment by jpasichnyk** [comment]
OOOH.  I pulled in your code and built it from github, and used that instead of Nuget package, and here is where it breaks..

in JobStoreClassMap.cs:

```
BsonClassMap.RegisterClassMap<JobKey>(map =>
            {
                map.AutoMap();
                map.MapCreator(jobKey => new JobKey(jobKey.Name));
                map.MapCreator(jobKey => new JobKey(jobKey.Name, jobKey.Group));
            });
```

and more specifically on:
```
map.AutoMap();
```

**Comment by chrisdrobison** [comment]
Interesting. All that is working for me. Are you using the abstract Key<> type anywhere in your code?

**Comment by jpasichnyk** [comment]
No, this breaks during initialization of the scheduler, before i get to do anything on my own even:

```var properties = new NameValueCollection
            {
                [StdSchedulerFactory.PropertySchedulerInstanceName] = "MassTransit_QuartzNet",
                [StdSchedulerFactory.PropertySchedulerInstanceId] = $"{Environment.MachineName}-{Guid.NewGuid()}",
                [StdSchedulerFactory.PropertyJobStoreType] = typeof(MongoDbJobStore).AssemblyQualifiedName,
                [
                    $"{StdSchedulerFactory.PropertyJobStorePrefix}.{StdSchedulerFactory.PropertyDataSourceConnectionString}"
                    ] = ConfigurationManager.ConnectionStrings["quartznet-mongodb"].ConnectionString,
                [$"{StdSchedulerFactory.PropertyJobStorePrefix}.collectionPrefix"] = "prefix"
            };
            // I treat the database in the connection string as the one you want to connect to
            // The prefix is optional

            var factory = new StdSchedulerFactory(properties);

            var MongoUrl = new MongoUrl(ConfigurationManager.ConnectionStrings["quartznet-mongodb"].ConnectionString);


            //BREAKS HERE
            var scheduler2 = factory.GetScheduler();
``

**Comment by chrisdrobison** [comment]
Which version of the driver are you using?

**Comment by jpasichnyk** [comment]
I have latest nuget for everything, and git master from yesterday on your driver.

**Comment by chrisdrobison** [comment]
Try an older 2.x driver and see if it works.

**Comment by jpasichnyk** [comment]
@chrisdrobison Wow, good call.  Running with MongoDB.* 2.2.0 NuGet packages, it runs! :)

EDIT: appears to work also up to 2.4.0.  2.4.1 seems to be the culprit. I'll update the title of this issue to reflect that.

**Comment by chrisdrobison** [comment]
I'll have to get some input from the driver authors about this issue then.
