### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by robertstefan** [glucaci/mongodb-quartz-net#8]
Interesting project, but it gives me a hard time while trying to make the configuration correct.

I want to run Quartz.NET scheduler as a Win service and MongoDB to be it's storage engine but I cannot make it work.

This is my Quartz config:
```
# You can configure your scheduler in either <quartz> configuration section
# or in quartz properties file
# Configuration section has precedence

quartz.scheduler.instanceName = ServerScheduler
#quartz.scheduler.instanceId = 726d6c6e-532e-4fc3-acb2-6e3f4b5a8f66

# configure thread pool info
quartz.threadPool.type = Quartz.Simpl.SimpleThreadPool, Quartz
quartz.threadPool.threadCount = 10
quartz.threadPool.threadPriority = Normal

# job initialization plugin handles our xml reading, without it defaults are used
#quartz.plugin.xml.type = Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin, Quartz
#quartz.plugin.xml.fileNames = ~/quartz_jobs.xml

quartz.jobStore.type = Quartz.Spi.MongoDbJobStore.MongoDbJobStore, Quartz
quartz.dataSource.connectionString = "mongodb://192.168.99.100:27017/quartz"
quartz.jobStore.useProperties = true

# export this server to remoting context
quartz.scheduler.exporter.type = Quartz.Simpl.RemotingSchedulerExporter, Quartz
quartz.scheduler.exporter.port = 555
quartz.scheduler.exporter.bindName = QuartzScheduler
quartz.scheduler.exporter.channelType = tcp
quartz.scheduler.exporter.channelName = httpQuartz
```

but when I start the WinService or run only in console mode, I get the following error log:

```
2017-07-13 22:04:08,991 [1] DEBUG Quartz.Server.QuartzServerFactory.CreateServer(c:\projects\quartznet\server\Quartz.Server\QuartzServerFactory.cs:24) - Creating new instance of server type 'Quartz.Server.QuartzServer, Quartz.Server, Version=2.5.0.400, Culture=neutral, PublicKeyToken=null'
2017-07-13 22:04:09,013 [1] DEBUG Quartz.Server.QuartzServerFactory.CreateServer(c:\projects\quartznet\server\Quartz.Server\QuartzServerFactory.cs:26) - Instance successfully created
2017-07-13 22:04:09,028 [1] INFO  Quartz.Impl.StdSchedulerFactory.Initialize(c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:231) - Quartz.NET properties loaded from configuration file 'C:\Program Files\Server.Net.Quartz\quartz.config'
2017-07-13 22:04:09,068 [1] ERROR Quartz.Server.QuartzServer.Initialize(c:\projects\quartznet\server\Quartz.Server\QuartzServer.cs:34) - Server initialization failed:Length cannot be less than zero.
Parameter name: length
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Quartz.Util.PropertiesParser.GetPropertyGroups(String prefix) in c:\projects\quartznet\src\Quartz\Util\PropertiesParser.cs:line 582
   at Quartz.Impl.StdSchedulerFactory.Instantiate() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 535
   at Quartz.Impl.StdSchedulerFactory.GetScheduler() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 1121
   at Quartz.Server.QuartzServer.Initialize() in c:\projects\quartznet\server\Quartz.Server\QuartzServer.cs:line 34
```

What am I missing from the config file ?

**Comment by chrisdrobison** [comment]
I run this in a windows service, but I don't use a config file, I config it in code. It looks like the error you are getting isn't specific to this library, but with Quartz.NET itself. Try doing configuration in code adding one at a time to see where it break.

**Comment by chrisdrobison** [comment]
You have the instance id commented out, is that on purpose?

**Comment by robertstefan** [comment]
Yes, as it was just for a test.
So, basically you mean to take the sources for Quartz.NET and then by trial-n-error.

**Comment by chrisdrobison** [comment]
How are you loading in the config file? As I recall, windows services set
the working directory to C:\Windows\System32 instead of the directory where
the executable is.

**Comment by robertstefan** [comment]
It seems it has an internal mechanism to set the working directory to the one where the exe is.


*Later edit:*
It seems that when using the config file, the section where declaring the data-source should contain:

```
quartz.jobStore.type = Quartz.Spi.MongoDbJobStore.MongoDbJobStore, Quartz
quartz.jobStore.useProperties = true
quartz.jobStore.dataSource = mongo
quartz.dataSource.myDS.provider = [....]
quartz.dataSource.mongo.connectionString = mongodb://127.0.0.1:27017/quartz
```

This is the log file contents:
```
Topshelf v3.1.135.0, .NET Framework v4.0.30319.42000
2017-07-16 14:27:56,240 [1] INFO  Quartz.Impl.StdSchedulerFactory.Initialize(c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:231) - Quartz.NET properties loaded from configuration file 'D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\bin\quartz.config'
2017-07-16 14:27:56,309 [1] ERROR Quartz.Server.QuartzServer.Initialize(D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:34) - Server initialization failed:Provider not specified for DataSource: mongo
Quartz.SchedulerException: Provider not specified for DataSource: mongo
   at Quartz.Impl.StdSchedulerFactory.Instantiate() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 587
   at Quartz.Impl.StdSchedulerFactory.GetScheduler() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 1121
   at Quartz.Server.QuartzServer.GetScheduler() in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:line 49
   at Quartz.Server.QuartzServer.Initialize() in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:line 34
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.ServiceBuilderException: An exception occurred creating the service: QuartzServer ---> Quartz.SchedulerException: Provider not specified for DataSource: mongo
   at Quartz.Impl.StdSchedulerFactory.Instantiate() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 587
   at Quartz.Impl.StdSchedulerFactory.GetScheduler() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 1121
   at Quartz.Server.QuartzServer.GetScheduler() in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:line 49
   at Quartz.Server.QuartzServer.Initialize() in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:line 39
   at Quartz.Server.Program.<>c.<Main>b__0_1(HostSettings factory) in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\Program.cs:line 30
   at Topshelf.Builders.ControlServiceBuilder`1.Build(HostSettings settings)
   --- End of inner exception stack trace ---
   at Topshelf.Builders.ControlServiceBuilder`1.Build(HostSettings settings)
   at Topshelf.Builders.RunBuilder.Build(ServiceBuilder serviceBuilder)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.ServiceBuilderException: An exception occurred creating the service: QuartzServer ---> Quartz.SchedulerException: Provider not specified for DataSource: mongo
   at Quartz.Impl.StdSchedulerFactory.Instantiate() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 587
   at Quartz.Impl.StdSchedulerFactory.GetScheduler() in c:\projects\quartznet\src\Quartz\Impl\StdSchedulerFactory.cs:line 1121
   at Quartz.Server.QuartzServer.GetScheduler() in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:line 49
   at Quartz.Server.QuartzServer.Initialize() in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\QuartzServer.cs:line 39
   at Quartz.Server.Program.<>c.<Main>b__0_1(HostSettings factory) in D:\Projects\Nightly Builds\Advanced Personal Assistant\Assistant.Service\server\Quartz.Server\Program.cs:line 30
   at Topshelf.Builders.ControlServiceBuilder`1.Build(HostSettings settings)
   --- End of inner exception stack trace ---
   at Topshelf.Builders.ControlServiceBuilder`1.Build(HostSettings settings)
   at Topshelf.Builders.RunBuilder.Build(ServiceBuilder serviceBuilder)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
```

After some Google searches I came around to [this post](https://stackoverflow.com/a/43329462/892190), but it's as far as I could get. It still doesn't work. 😢

**Comment by dmumladze** [comment]
Can you try defining configuratoins in App.config like so

```
  <configSections>
    <section name="quartz" type="System.Configuration.NameValueSectionHandler"/>
  </configSections>
```
Then actual configs

```
  <quartz>
    <add key="quartz.threadPool.threadCount" value="100"/>
    <add key="quartz.plugin.triggHistory.type" value="Quartz.Plugin.History.LoggingJobHistoryPlugin"/>
    <add key="quartz.plugin.jobInitializer.type" value="Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin"/>
    <add key="quartz.plugin.jobInitializer.fileNames" value="Quartz-Jobs.config"/>
    <add key="quartz.plugin.jobInitializer.failOnFileNotFound" value="true"/>
  </quartz>
```

And then in code

```
  var config = (NameValueCollection)ConfigurationManager.GetSection("quartz");
  var factory = new StdSchedulerFactory(config);
  IScheduler scheduler = factory.GetScheduler();
  scheduler.Start();
```

**Comment by enderdickerson** [comment]
@dmumladze @robertstefan I see that this solution might have worked for you. Where did you end up specifying the connection string property?

**Comment by dmumladze** [comment]
@enderdickerson Can you try? 

```
  <quartz>
    <add key="quartz.dataSource.mongo.connectionString" value="mongodb://127.0.0.1:27017/quartz"/>
  </quartz>
```

**Comment by robertstefan** [comment]
@enderdickerson i ended using smth like the following:

```xml
<connectionStrings>
	<clear />
	<add name="mongo" connectionString="mongodb://192.168.99.100/quartz" />
  </connectionStrings>
```

```csharp
var properties = new NameValueCollection {
/// ....
    [StdSchedulerFactory.PropertyJobStoreType] = typeof(MongoDbJobStore).AssemblyQualifiedName,
	[$"{StdSchedulerFactory.PropertyJobStorePrefix}.{StdSchedulerFactory.PropertyDataSourceConnectionString}"] = ConfigurationManager.ConnectionStrings["mongo"].ConnectionString
/// ...
};
```
